import type { Metadata } from "next";
import {Black_Han_Sans} from "next/font/google";
import "./globals.css";

const blackHanSans = Black_Han_Sans({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={blackHanSans.className}
      >
        {children}
      </body>
    </html>
  );
}
